listener {
    timeout = 3600                    # Time in seconds
    on-timeout = brightnessctl set 0%            # Runs when idle period ends
    on-resume = brightnessctl set 100%              # Runs when user returns
}
